### ISSUE TITLE
Dynamic content un-stickies footer

### ISSUE THREAD

**Issue by lusa** [mahmoud/skeleton_sticky_footer#2]
Hello, I appreciate the work here so far, it works great with static content. However when new elements are added that increase the height, the footer gets pushed further down the page. How can I lock the heights so the footer stays at the bottom? It seems that when any scrolling is involved, the footer will move with the page.

**Comment by mahmoud** [comment]
Right, that's the behavior of a sticky footer. I think what you're looking for is a "fixed" footer, which stays at the bottom of the _window_, not the bottom of the _page_. 

Confusing, I know, but web design is a vocabulary circus. :)

**Comment by lusa** [comment]
Ah, I guess I need to get up on my design terminology then! Thanks..

**Comment by mahmoud** [comment]
Hehe, yes, just remember that this footer is sticky and the `fixed` footer is _stuck_. ;)
