### ISSUE TITLE
Missing close div

### ISSUE THREAD

**Issue by whirlgirlz** [mahmoud/skeleton_sticky_footer#3]
The div 'table-container' has not been closed. Once closed, it breaks the full-width footer.

**Comment by mahmoud** [comment]
Hey! You're right, that tag was unclosed! I've fixed it. I'm not sure what you mean about breaking the full-width footer. The footer wasn't necessarily stylized as full-width, just sticky. That said, a full-width background to the footer would look best. Any advice on that?

**Comment by whirlgirlz** [comment]
Hi! Thanks for looking at this. 

I've attached a couple of images - before and after the closed div. Before, the footer was full width and centered. After, the footer is just one column at the left of the page. In addition, I get a vertical scrollbar on the page.

But the footer is still sticky. The problem is I can't seem to get it out of this single column and to span the page width.

![before](https://cloud.githubusercontent.com/assets/14790856/10026811/08fa2956-6121-11e5-9252-19438dde1127.png)
![after](https://cloud.githubusercontent.com/assets/14790856/10026810/08f53e46-6121-11e5-8cca-f134cced4e5c.png)

**Comment by mahmoud** [comment]
Yeah, I getcha. I've had this happen with Skeleton before. That said, it's working on my Chromium and my Firefox 40:

![sticky_footer](https://cloud.githubusercontent.com/assets/130193/10029558/67e26d2e-6127-11e5-8dd6-e6a820f5991a.png)

As you can see, not-quite-full width, but twelve columns and no scrollbar. Did you try pulling the fixed version?
